{"message":"User already exists","stack":"Error: User already exists\n    at /app/controllers/authController.js:32:15\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}